project_id = "apfjafxiykkiydepmswk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.savio-webhook]
    verify_jwt = false
  [functions.slack-events]
    verify_jwt = false
  [functions.microsoft-auth]
    verify_jwt = false
  [functions.microsoft-callback]
    verify_jwt = false
  [functions.microsoft-api]
    verify_jwt = false
  [functions.dropbox-token-exchange]
    verify_jwt = false
