project_id = "apfjafxiykkiydepmswk"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.savio-webhook]
    verify_jwt = false
  [functions.slack-events]
    verify_jwt = false
