-- =============================================================
-- AI Artifacts: documents generated by Claude during conversations
-- =============================================================

CREATE TABLE IF NOT EXISTS public.ai_artifacts (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    ai_project_id uuid,
    conversation_id uuid,
    user_id uuid NOT NULL,
    organization_id uuid NOT NULL,
    title text NOT NULL,
    content text NOT NULL,
    content_type text NOT NULL DEFAULT 'markdown',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ai_artifacts_pkey PRIMARY KEY (id),
    CONSTRAINT ai_artifacts_ai_project_id_fkey
        FOREIGN KEY (ai_project_id) REFERENCES public.ai_projects(id) ON DELETE SET NULL,
    CONSTRAINT ai_artifacts_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE,
    CONSTRAINT ai_artifacts_organization_id_fkey
        FOREIGN KEY (organization_id) REFERENCES public.organizations(id) ON DELETE CASCADE,
    CONSTRAINT ai_artifacts_content_type_check
        CHECK (content_type IN ('markdown', 'code', 'html', 'csv'))
);

CREATE INDEX IF NOT EXISTS idx_ai_artifacts_user
    ON public.ai_artifacts (user_id, organization_id);

CREATE INDEX IF NOT EXISTS idx_ai_artifacts_project
    ON public.ai_artifacts (ai_project_id)
    WHERE ai_project_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ai_artifacts_conversation
    ON public.ai_artifacts (conversation_id)
    WHERE conversation_id IS NOT NULL;

-- RLS
ALTER TABLE public.ai_artifacts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage their own artifacts"
    ON public.ai_artifacts FOR ALL
    USING (user_id = auth.uid())
    WITH CHECK (user_id = auth.uid());

CREATE POLICY "Service role full access artifacts"
    ON public.ai_artifacts FOR ALL
    USING (auth.role() = 'service_role')
    WITH CHECK (auth.role() = 'service_role');

-- Update document_chunks CHECK to include 'artifact'
DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.check_constraints
        WHERE constraint_name = 'document_chunks_source_type_check'
    ) THEN
        ALTER TABLE public.document_chunks DROP CONSTRAINT document_chunks_source_type_check;
    END IF;
END $$;

ALTER TABLE public.document_chunks
    ADD CONSTRAINT document_chunks_source_type_check
    CHECK (source_type IN ('document', 'extracted_data', 'chat_message', 'procedure', 'comunicado', 'memory', 'artifact'));
