-- ===========================================================
-- Kawiil OS — Seed compliance_entity_types y compliance_task_templates
-- Generado por Claude el 2026-05-04
-- Fuentes: Sylon — Matriz IFPE 2026 + Obligaciones Transmisores PPTX
-- ===========================================================

BEGIN;

-- -----------------------------------------------------------
-- 1) Entity types (idempotente: ON CONFLICT (code) DO NOTHING)
-- -----------------------------------------------------------
INSERT INTO compliance_entity_types (code, name, group_name, description)
VALUES
  ('ifpe', 'IFPE — Institución de Fondos de Pago Electrónico', 'CNBV / Banxico (LRITF)', 'Entidad regulada bajo la Ley para Regular las Instituciones de Tecnología Financiera (LRITF). Reporta a Banxico, CNBV, UIF/SHCP y Condusef.'),
  ('transmisor_dinero', 'Transmisor de Dinero', 'CNBV (LGOAAC)', 'Sociedad registrada como Transmisor de Dinero ante la CNBV bajo el art. 81-A Bis LGOAAC y Disposiciones de carácter general SHCP/CNBV en materia PLD/FT.'),
  ('av_general', 'Actividad Vulnerable — General', 'SAT / UIF (LFPIORPI)', 'Persona física o moral que realiza alguna de las Actividades Vulnerables del art. 17 LFPIORPI. Reporta avisos al SAT (canal UIF). Aplica el Reglamento reformado (DOF 27-mar-2026).')
ON CONFLICT (code) DO UPDATE SET
  name        = EXCLUDED.name,
  group_name  = EXCLUDED.group_name,
  description = EXCLUDED.description;

-- -----------------------------------------------------------
-- 2) Task templates
-- Resolvemos entity_type_id vía subquery por code para no
-- depender del orden de inserción ni de UUIDs hardcodeados.
-- -----------------------------------------------------------
-- LIMPIEZA OPCIONAL (solo activos seedeados): comenta si no quieres reemplazar
-- DELETE FROM compliance_task_templates
--  WHERE entity_type_id IN (
--    SELECT id FROM compliance_entity_types WHERE code IN ('ifpe','transmisor_dinero','av_general')
--  );

INSERT INTO compliance_task_templates (
  entity_type_id, task_name, description, category, periodicity,
  due_day, due_month, due_month_2, due_description, legal_basis, sort_order, is_active
) VALUES
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Banxico — ACM IFPE Sección 1 (Catálogo Mínimo)',
   'Envío mensual del Formulario Catálogo Mínimo (Paquete I, Sección 1) a través de SAIFWeb Banxico. Responsable interno: Contabilidad.',
   'reportes_banxico',
   'mensual',
   14,
   NULL,
   NULL,
   'Décimo día hábil del mes inmediato siguiente, antes de las 14:00 hrs.',
   'Circular Banxico aplicable a IFPEs — Reportes Regulatorios; Anexo Catálogo Mínimo.',
   110,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Banxico — ACM IFPE Sección 2 (Anexo del Catálogo Mínimo)',
   'Envío mensual del Anexo del Catálogo Mínimo (Paquete I, Sección 2) a través de SAIFWeb Banxico.',
   'reportes_banxico',
   'mensual',
   14,
   NULL,
   NULL,
   'Décimo día hábil del mes inmediato siguiente, antes de las 14:00 hrs.',
   'Circular Banxico aplicable a IFPEs — Reportes Regulatorios.',
   120,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Banxico — CUFPE (Cuentas de Fondos de Pago Electrónico)',
   'Formulario CUFPE (Paquete I, Secciones I–VI). Información de cuentas de fondos de pago electrónico. Responsables internos: TI + Contabilidad.',
   'reportes_banxico',
   'mensual',
   14,
   NULL,
   NULL,
   'Décimo día hábil del mes inmediato siguiente, antes de las 14:00 hrs.',
   'Circular Banxico aplicable a IFPEs — Reportes Regulatorios.',
   130,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R01 / R01 A-0111 (Catálogo Mínimo)',
   'Reporte regulatorio R01 A-0111 vía API Suptech.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Capítulo de Reportes Regulatorios; Catálogo Mínimo CNBV.',
   210,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R08 / R08 D-0843 (Préstamos obtenidos)',
   'Desagregado de préstamos bancarios y de otros organismos.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Reportes Regulatorios Serie R08.',
   220,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R10 A-10111 (Reclasificaciones — situación financiera)',
   'Reclasificaciones en el estado de situación financiera.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R10 Reclasificaciones.',
   230,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R10 A-10121 (Reclasificaciones — resultado integral)',
   'Reclasificaciones en el estado de resultado integral.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R10 Reclasificaciones.',
   240,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R13 A-13111 (Estado de cambios en el capital contable)',
   'Estado de cambios en el capital contable — entrega trimestral.',
   'reportes_cnbv',
   'trimestral',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente al cierre del trimestre.',
   'DCG aplicables a las IFPEs — Serie R13 Estados Financieros.',
   250,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R13 A-13161 (Estado de flujos de efectivo)',
   'Estado de flujos de efectivo — entrega trimestral.',
   'reportes_cnbv',
   'trimestral',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente al cierre del trimestre.',
   'DCG aplicables a las IFPEs — Serie R13 Estados Financieros.',
   260,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R13 B-13211 (Estado de situación financiera)',
   'Estado de situación financiera mensual.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R13 Estados Financieros.',
   270,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R13 B-13221 (Estado de resultado integral)',
   'Estado de resultado integral mensual.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R13 Estados Financieros.',
   280,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R24 / G-2470 (Información de clientes y operaciones)',
   'Información operativa relativa a clientes y operaciones — vía API SITI Analítica.',
   'reportes_cnbv',
   'mensual',
   14,
   NULL,
   NULL,
   'Décimo día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R24 Información operativa.',
   290,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R26 A-2610 (Altas/bajas administradores de comisionistas)',
   'Altas y bajas de administradores de comisionistas.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R26 Comisionistas.',
   300,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R26 A-2611 (Desagregado altas/bajas de comisionistas)',
   'Desagregado de altas y bajas de comisionistas.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R26 Comisionistas.',
   310,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R26 B-2612 (Desagregado de módulos/establecimientos de comisionistas)',
   'Desagregado de altas y bajas de módulos o establecimientos de comisionistas.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R26 Comisionistas.',
   320,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R26 C-2613 (Seguimiento de operaciones de comisionistas)',
   'Desagregado del seguimiento de operaciones de comisionistas.',
   'reportes_cnbv',
   'mensual',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente.',
   'DCG aplicables a las IFPEs — Serie R26 Comisionistas.',
   330,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'CNBV — Serie R27 A-2701 (Reclamaciones)',
   'Reporte trimestral de reclamaciones — UNE.',
   'reportes_cnbv',
   'trimestral',
   28,
   NULL,
   NULL,
   'Último día hábil del mes inmediato siguiente al cierre del trimestre.',
   'DCG aplicables a las IFPEs — Serie R27 Reclamaciones.',
   340,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'UIF — Reporte de Operaciones Relevantes (ROR)',
   'ROR trimestral de operaciones en efectivo y con dólares de EUA u otras divisas iguales o superiores al umbral.',
   'reportes_uif',
   'trimestral',
   21,
   NULL,
   NULL,
   'Dentro de los diez últimos días hábiles de los meses de enero, abril, julio y octubre de cada año.',
   'Disposiciones de carácter general a que se refieren los artículos 71 frac. VII y XIV, y 72 a 87 LRITF — DOF 10-sep-2018.',
   410,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'UIF — Reporte de Operaciones Inusuales (ROI)',
   'Reporte de operaciones que el sistema PLD detecte como inusuales tras la generación de la alerta.',
   'reportes_uif',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de un periodo que no exceda 60 días naturales contados a partir de que se genere la alerta.',
   'Disposiciones LRITF en materia PLD/FT — DOF 10-sep-2018; reformas aplicables.',
   420,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'UIF — Reporte de Operaciones Internas Preocupantes (ROIP)',
   'Reporte de operaciones internas preocupantes detectadas en colaboradores, directivos o accionistas.',
   'reportes_uif',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de un periodo que no exceda 60 días naturales contados a partir de que se genere la alerta.',
   'Disposiciones LRITF en materia PLD/FT — DOF 10-sep-2018.',
   430,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'UIF — Reporte de Transferencias Internacionales de Fondos (RTIF)',
   'Reporte mensual de transferencias internacionales de fondos enviadas o recibidas en el mes inmediato anterior.',
   'reportes_uif',
   'mensual',
   21,
   NULL,
   NULL,
   'Mensualmente, a más tardar dentro de los 15 días hábiles siguientes al último día hábil del mes inmediato anterior.',
   'Disposiciones LRITF en materia PLD/FT — Capítulo de transferencias internacionales.',
   440,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Comité de Comunicación y Control — Información anual de integración/cambios',
   'Aviso a la autoridad respecto de la integración y cambios en el Comité de Comunicación y Control.',
   'gobierno_corporativo',
   'anual',
   21,
   1,
   NULL,
   'Dentro de los primeros 15 días hábiles del mes de enero de cada año.',
   'Disposiciones LRITF en materia PLD/FT — capítulo Comité de Comunicación y Control.',
   510,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Oficial de Cumplimiento — Aviso de designación o cambio',
   'Aviso a la autoridad sobre el nombramiento, sustitución o ratificación del Oficial de Cumplimiento.',
   'gobierno_corporativo',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de los 15 días hábiles siguientes a la fecha en que se haya efectuado el nombramiento.',
   'Disposiciones LRITF en materia PLD/FT — Oficial de Cumplimiento.',
   520,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Manual PLD/FT — Aviso de modificaciones',
   'Notificación a la autoridad de las modificaciones aprobadas al Documento de políticas de identificación y conocimiento del Cliente y Usuario (Manual).',
   'politicas',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de los 20 días hábiles siguientes a la fecha en que el Comité de Auditoría apruebe la modificación.',
   'Disposiciones LRITF en materia PLD/FT — Manual.',
   530,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Auditoría anual PLD/FT — Informe a la autoridad',
   'Resultados de la revisión anual por parte del área de auditoría interna o auditor externo independiente para evaluar el cumplimiento a las Disposiciones PLD/FT.',
   'auditoria',
   'anual',
   28,
   2,
   NULL,
   'Dentro de los 60 días siguientes al cierre del ejercicio al que corresponda la revisión.',
   'Disposiciones LRITF en materia PLD/FT — Auditoría.',
   540,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Capacitación PLD/FT — Programa anual de cursos',
   'Informe que contenga el programa anual de cursos de capacitación en materia PLD/FT.',
   'capacitacion',
   'anual',
   21,
   1,
   NULL,
   'Dentro de los primeros 15 días hábiles de enero de cada año.',
   'Disposiciones LRITF en materia PLD/FT — Capacitación.',
   550,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Condusef — REUNE (Reporte de reclamaciones a Unidades Especializadas)',
   'Reporte estadístico trimestral de reclamaciones presentadas ante la UNE.',
   'reportes_condusef',
   'trimestral',
   30,
   NULL,
   NULL,
   'Dentro de los 30 días naturales siguientes al cierre del trimestre.',
   'Disposiciones de carácter general en materia de transparencia y de sanas prácticas — Condusef; Ley de Protección y Defensa al Usuario de Servicios Financieros.',
   610,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Condusef — REDECO (Despachos de cobranza)',
   'Registro y reporte de despachos de cobranza contratados, conforme a la regulación Condusef.',
   'reportes_condusef',
   'mensual',
   10,
   NULL,
   NULL,
   'Dentro de los primeros 10 días naturales del mes inmediato siguiente.',
   'Disposiciones generales aplicables al REDECO — Condusef.',
   620,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Condusef — RECO (Registro de Comisiones)',
   'Actualización del Registro de Comisiones ante Condusef cuando haya altas, bajas o modificaciones.',
   'reportes_condusef',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Conforme al plazo establecido en las Disposiciones Condusef RECO al modificar el catálogo de comisiones.',
   'Disposiciones de carácter general aplicables al RECO — Condusef.',
   630,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Condusef — Buró de Entidades Financieras (BEF)',
   'Mantener actualizada la información de la entidad y sus productos en el Buró de Entidades Financieras.',
   'reportes_condusef',
   'anual',
   31,
   3,
   NULL,
   'Actualización al cierre del ejercicio inmediato anterior; entrega típica primer trimestre del año siguiente.',
   'Lineamientos del Buró de Entidades Financieras — Condusef.',
   640,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'SAT — Declaración mensual ISR / IVA / Retenciones',
   'Pago provisional mensual de ISR e IVA + retenciones según corresponda.',
   'fiscal',
   'mensual',
   17,
   NULL,
   NULL,
   'A más tardar el día 17 del mes inmediato siguiente al periodo declarado (con días adicionales por sexto dígito del RFC, conforme calendario).',
   'CFF, LISR, LIVA y Resolución Miscelánea Fiscal vigente.',
   710,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'SAT — Declaración Anual de Personas Morales',
   'Declaración anual de ISR de personas morales del régimen general.',
   'fiscal',
   'anual',
   31,
   3,
   NULL,
   'A más tardar el 31 de marzo del año inmediato siguiente al ejercicio.',
   'Art. 76 fracción V LISR.',
   720,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'SAT — DIOT (Declaración Informativa de Operaciones con Terceros)',
   'Declaración informativa de operaciones con proveedores.',
   'fiscal',
   'mensual',
   31,
   NULL,
   NULL,
   'Último día del mes inmediato siguiente al periodo a declarar.',
   'Art. 32 fracción VIII LIVA y Resolución Miscelánea vigente.',
   730,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Conservación de expedientes de identificación — 10 años',
   'Resguardo del expediente de identificación del cliente y de los soportes de operaciones por 10 años contados a partir del cierre de la operación o relación.',
   'conservacion',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Diez años contados a partir de la fecha de la operación o del cierre de la cuenta/relación, según corresponda.',
   'Disposiciones LRITF en materia PLD/FT — capítulo de Conservación.',
   810,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'ifpe'),
   'Revisión anual del expediente de identificación de Clientes (KYC refresh)',
   'Revisión y, en su caso, actualización del expediente de identificación de clientes y beneficiarios controladores.',
   'kyc',
   'anual',
   31,
   12,
   NULL,
   'Al menos una vez por ejercicio, conforme al Manual.',
   'Disposiciones LRITF en materia PLD/FT — capítulo de Identificación del Cliente.',
   820,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'UIF — Comité de Comunicación y Control: aviso anual de integración/cambios',
   'Información respecto de la integración y cambios en el Comité de Comunicación y Control.',
   'gobierno_corporativo',
   'anual',
   21,
   1,
   NULL,
   'Dentro de los primeros 15 días hábiles del mes de enero de cada año.',
   'Disposiciones de carácter general a que se refiere el art. 95 Bis LGOAAC — Comité de Comunicación y Control.',
   110,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'UIF — Oficial de Cumplimiento: aviso de designación/cambio',
   'Aviso de nombramiento, sustitución o ratificación del Oficial de Cumplimiento.',
   'gobierno_corporativo',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de los 15 días hábiles siguientes a la fecha del nombramiento correspondiente.',
   'Disposiciones art. 95 Bis LGOAAC — Oficial de Cumplimiento.',
   120,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'UIF — Reporte de Operaciones Relevantes (ROR)',
   'Reporte trimestral de operaciones relevantes (efectivo y divisas iguales o superiores a umbral).',
   'reportes_uif',
   'trimestral',
   21,
   NULL,
   NULL,
   'Dentro de los diez últimos días hábiles de los meses de enero, abril, julio y octubre de cada año.',
   'Disposiciones art. 95 Bis LGOAAC — ROR.',
   210,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'UIF — Reporte de Operaciones Inusuales (ROI) y Operaciones Internas Preocupantes (ROIP)',
   'Reporte de operaciones inusuales detectadas y operaciones internas preocupantes.',
   'reportes_uif',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de un periodo que no exceda 60 días naturales contados a partir de que se genere la alerta.',
   'Disposiciones art. 95 Bis LGOAAC — ROI y ROIP.',
   220,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'UIF — Reporte de Transferencias Internacionales de Fondos (RTIF)',
   'Reporte mensual de transferencias internacionales enviadas o recibidas.',
   'reportes_uif',
   'mensual',
   21,
   NULL,
   NULL,
   'Mensualmente, a más tardar dentro de los 15 días hábiles siguientes al último día hábil del mes inmediato anterior.',
   'Disposiciones art. 95 Bis LGOAAC — RTIF.',
   230,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Manual PLD/FT — Aviso de modificaciones',
   'Notificación de las modificaciones aprobadas al Documento de políticas de identificación y conocimiento del Cliente y Usuario (Manual).',
   'politicas',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de los 20 días hábiles siguientes a la fecha en que el Comité de Auditoría apruebe la modificación.',
   'Disposiciones art. 95 Bis LGOAAC — Manual.',
   310,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Auditoría anual PLD/FT — Informe a la autoridad',
   'Resultados de la revisión anual de auditoría interna o externa independiente para evaluar el cumplimiento PLD/FT.',
   'auditoria',
   'anual',
   28,
   2,
   NULL,
   'Dentro de los 60 días siguientes al cierre del ejercicio al que corresponda la revisión.',
   'Disposiciones art. 95 Bis LGOAAC — Auditoría.',
   320,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Capacitación PLD/FT — Programa anual de cursos',
   'Informe que contenga el programa anual de cursos de capacitación en materia PLD/FT.',
   'capacitacion',
   'anual',
   21,
   1,
   NULL,
   'Dentro de los primeros 15 días hábiles de enero de cada año.',
   'Disposiciones art. 95 Bis LGOAAC — Capacitación.',
   330,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Lista anual de Agentes Relacionados y terceros',
   'Lista de Agentes Relacionados con los que se tiene relación contractual, así como los terceros con los que operan los Agentes Relacionados.',
   'gobierno_corporativo',
   'anual',
   21,
   1,
   NULL,
   'Dentro de los primeros 15 días hábiles de cada año.',
   'Disposiciones art. 95 Bis LGOAAC — Agentes Relacionados.',
   410,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Aviso anual sobre cambios en el control accionario',
   'Informe sobre los cambios en la información respecto de la identidad de la persona o grupo de personas que ejerzan el control en la Sociedad.',
   'gobierno_corporativo',
   'anual',
   21,
   1,
   NULL,
   'Dentro de los primeros 15 días hábiles de cada año.',
   'Disposiciones art. 95 Bis LGOAAC — Control accionario.',
   420,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Aviso de transmisión de acciones por más del 2% del capital',
   'Informe sobre la transmisión de cualquiera de sus acciones por más del 2% del capital social pagado.',
   'gobierno_corporativo',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de los 3 días hábiles siguientes a aquel en que se haya inscrito en el registro.',
   'Disposiciones art. 95 Bis LGOAAC — Transmisión de acciones.',
   430,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'CNBV — Renovación anual del registro de Transmisor de Dinero',
   'Mantener vigente el registro como Transmisor de Dinero ante CNBV; cumplir con requisitos y, en su caso, ratificación periódica.',
   'gobierno_corporativo',
   'anual',
   30,
   6,
   NULL,
   'Conforme a la fecha aniversario del registro y a los plazos de las Reglas de Operación CNBV.',
   'Art. 81-A Bis LGOAAC y Reglas de Operación de Transmisores de Dinero — CNBV.',
   510,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'CNBV — Reporte semestral de operaciones (Transmisores)',
   'Reporte de operaciones de envío y recepción de transferencias de fondos conforme a las Reglas de Operación CNBV.',
   'reportes_cnbv',
   'semestral',
   30,
   1,
   7,
   'Dentro del mes siguiente al cierre del semestre, conforme a las Reglas de Operación CNBV.',
   'Reglas de Operación de Transmisores de Dinero — CNBV.',
   520,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Condusef — REUNE (Reclamaciones a UNE)',
   'Reporte trimestral de reclamaciones recibidas por la Unidad Especializada.',
   'reportes_condusef',
   'trimestral',
   30,
   NULL,
   NULL,
   'Dentro de los 30 días naturales siguientes al cierre del trimestre.',
   'Ley de Protección y Defensa al Usuario de Servicios Financieros y Disposiciones Condusef.',
   610,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'SAT — Declaración mensual ISR / IVA / Retenciones',
   'Pago provisional mensual de ISR e IVA + retenciones.',
   'fiscal',
   'mensual',
   17,
   NULL,
   NULL,
   'A más tardar el día 17 del mes inmediato siguiente al periodo declarado.',
   'CFF, LISR, LIVA y Resolución Miscelánea Fiscal vigente.',
   710,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'SAT — Declaración Anual de Personas Morales',
   'Declaración anual de ISR de personas morales.',
   'fiscal',
   'anual',
   31,
   3,
   NULL,
   'A más tardar el 31 de marzo del año inmediato siguiente al ejercicio.',
   'Art. 76 fracción V LISR.',
   720,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'SAT — DIOT (Declaración Informativa de Operaciones con Terceros)',
   'Declaración informativa de operaciones con proveedores.',
   'fiscal',
   'mensual',
   31,
   NULL,
   NULL,
   'Último día del mes inmediato siguiente al periodo a declarar.',
   'Art. 32 fracción VIII LIVA y Resolución Miscelánea vigente.',
   730,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Conservación de expedientes de identificación — 10 años',
   'Resguardo del expediente de identificación del Cliente y de soportes de operaciones por 10 años.',
   'conservacion',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Diez años contados a partir de la fecha de la operación o cierre de la relación.',
   'Disposiciones art. 95 Bis LGOAAC — Conservación.',
   810,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'transmisor_dinero'),
   'Revisión anual del expediente de identificación (KYC refresh)',
   'Revisión y, en su caso, actualización del expediente de identificación de Clientes y Beneficiarios Controladores.',
   'kyc',
   'anual',
   31,
   12,
   NULL,
   'Al menos una vez por ejercicio conforme al Manual.',
   'Disposiciones art. 95 Bis LGOAAC — Identificación del Cliente.',
   820,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'SAT/UIF — Aviso mensual de Actividad Vulnerable',
   'Presentación mensual del Aviso de Actos u Operaciones realizadas en el mes inmediato anterior, vía Portal de Prevención de Lavado de Dinero.',
   'avisos_sat',
   'mensual',
   17,
   NULL,
   NULL,
   'A más tardar el día 17 del mes inmediato siguiente a aquél en que se realizó el acto u operación.',
   'Art. 23 LFPIORPI; art. 23 Reglamento LFPIORPI.',
   110,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'UIF — Aviso de operaciones intentadas (Art. 7 Bis Reglamento)',
   'Reporte de operaciones intentadas por el cliente o usuario que no se concretaron, conforme a la reforma 2026.',
   'avisos_sat',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Dentro de las 24 horas siguientes a que se conozca el intento de operación.',
   'Art. 7 Bis Reglamento LFPIORPI — reforma DOF 27-mar-2026.',
   120,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Identificación de PPE (Personas Políticamente Expuestas) — Procedimiento',
   'Aplicación del procedimiento de identificación de PPE nacionales y extranjeras conforme a las reformas 2026.',
   'kyc',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Al alta del cliente y al detectar cambios en su estatus.',
   'Reglamento LFPIORPI — reforma DOF 27-mar-2026 (PPE ampliadas).',
   130,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Manual PLD-AV — Revisión y actualización anual',
   'Revisión y, en su caso, actualización del Manual de PLD para Actividades Vulnerables, incluyendo PPE, conservación y procedimientos vigentes.',
   'politicas',
   'anual',
   31,
   1,
   NULL,
   'Al menos una vez por ejercicio.',
   'Art. 18 fracción VI LFPIORPI; Reglamento LFPIORPI.',
   210,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Capacitación anual en materia PLD-AV',
   'Programa y ejecución de capacitación anual en PLD-AV al personal responsable.',
   'capacitacion',
   'anual',
   31,
   12,
   NULL,
   'Al menos una vez por ejercicio.',
   'Art. 20 LFPIORPI y Reglamento.',
   220,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Auditoría interna PLD-AV — Documentación anual',
   'Documentación de la revisión interna anual del cumplimiento PLD-AV.',
   'auditoria',
   'anual',
   31,
   3,
   NULL,
   'Dentro del primer trimestre del año siguiente al ejercicio revisado.',
   'Reglamento LFPIORPI — reforma 2026 (facultades ampliadas SAT).',
   230,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Conservación de expedientes — 5 años (LFPIORPI)',
   'Resguardo de la información de identificación de clientes/usuarios y soportes de operaciones por 5 años.',
   'conservacion',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Cinco años contados a partir de la fecha de la operación o del cierre de la relación.',
   'Art. 18 fracción V LFPIORPI; Reglamento (plazos actualizados 2026).',
   310,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Designación / actualización del Encargado de Cumplimiento',
   'Designación o actualización del Encargado de Cumplimiento (cuando aplique según tipo y tamaño de la AV).',
   'gobierno_corporativo',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Al alta como AV y al sustituir al encargado.',
   'Art. 20 LFPIORPI y Reglamento.',
   320,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'RFC — Alineación de domicilio fiscal y actualización',
   'Mantener el domicilio fiscal del RFC alineado con el domicilio real, conforme a los criterios reforzados 2026.',
   'fiscal',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Al detectar discrepancia o cambio de domicilio.',
   'Art. 27 CFF y criterios SAT 2026.',
   410,
   true),
  ((SELECT id FROM compliance_entity_types WHERE code = 'av_general'),
   'Alta o actualización de cuenta en el Portal PLD (SAT)',
   'Alta inicial o actualización del enrolamiento de la persona física/moral en el Portal de Prevención de Lavado de Dinero.',
   'avisos_sat',
   'cuando_aplique',
   NULL,
   NULL,
   NULL,
   'Al iniciar la AV o al modificar datos del enrolamiento.',
   'Art. 17 y 18 LFPIORPI; Reglas de Carácter General LFPIORPI.',
   420,
   true)
;

COMMIT;

-- ===========================================================
-- Verificación rápida
-- ===========================================================
-- SELECT et.code, COUNT(*) AS n_templates
--   FROM compliance_task_templates t
--   JOIN compliance_entity_types  et ON et.id = t.entity_type_id
--  WHERE et.code IN ('ifpe','transmisor_dinero','av_general')
--  GROUP BY et.code ORDER BY et.code;